### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by branfosj** [easybuilders/easybuild-docs#134]
A page can be boosted in the search by adding YAML:
```yaml
---
search:
  boost: 2 
---
```
Similarly, that can be `boost: 0.5` to down rank a page.

Also, experimental support for excluding a page from the search:
```yaml
---
search:
  exclude: true
---
```
or a section:
```md
## Section 2 { data-search-exclude }
```

These are all from https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/
